repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: local
    hooks:
    - id: build
      name: Generate GitHub page
      description: This hook regenerates GitHub page.
      entry: make
      pass_filenames: false
      always_run: true
      language: system
  - repo: https://github.com/rtts/djhtml
    rev: "3.0.7"
    hooks:
      - id: djhtml
        entry: djhtml --tabwidth 2
      - id: djcss
  - repo: https://github.com/tcort/markdown-link-check
    rev: "v3.12.2"
    hooks:
      - id: markdown-link-check
  - repo: https://github.com/shssoichiro/oxipng
    rev: "v9.1.2"
    hooks:
      - id: oxipng
        args: ["-o", "max", "--strip", "safe"]

ci:
  skip:
    - build
    - markdown-link-check
    - oxipng
